#!/bin/bash
# 
# This script downloads a user's tweets by year.
#

# Errors are fatal
set -e

#
# Change to where this script is
#
pushd $(dirname $0) > /dev/null

#
# Sanity check for our username.
#
if test ! "$3"
then
	echo "! "
	echo "! Syntax: $0 username start_year end_year [ options ]"
	echo "! "
	exit 1
fi

USER=$1
YEAR_START=$2
YEAR_STOP=$3

if test $YEAR_STOP -lt $YEAR_START
then
	echo "! "
	echo "! Stopping year '${YEAR_STOP}' cannot be less than starting year '${YEAR_START}'!"
	echo "! "
	exit 1
fi


for YEAR in $(seq $YEAR_START $YEAR_STOP)
do

	echo "# "
	echo "# Starting download of tweets for user from year ${YEAR}..."
	echo "# "
	./twint-user ${USER} --since ${YEAR}-01-01 --until $((YEAR + 1))-01-01
	echo "# "
	echo "# Done with year ${YEAR}!"
	echo "# "

done

echo "# Done with downloading tweets for ${USER} from ${YEAR_START} to ${YEAR_STOP}!"

