#!/bin/bash
#
# Download and run the Twint Docker image.
#

# Errors are fatal
set -e

#
# Are we running the full version? (Lite version by default)
#
NAME="dmuth1/twint"
FULL=""
if test "$1" == "full"
then
	NAME="dmuth1/twint-full"
	FULL="full"
	shift
fi

#
# Check to see if we have our image. If we don't, fetch it.
#
# TODO: In the future, I should add some logic to try fetching 
#	again if the image is too old.
#
IMAGE=$(docker images | egrep "^${NAME} " | grep latest || true)

if test ! "${IMAGE}"
then
	echo "# Docker image ${NAME} not found, downloading..."
	docker pull ${NAME}
fi

#
# Now run our image with the passed in arguments.
# Point /mnt to the current directory so files can be written.
#
echo "# "
echo "# You are running Twint Splunk, built from: https://github.com/dmuth/twint-splunk"
echo "# Go to https://github.com/twintproject/twint for the official webpage and documentation."
echo "# "
docker run -v $(pwd):/mnt ${NAME} $@


