#!/bin/bash
# 
# This script downloads a user's tweets by year.
#

# Errors are fatal
set -e

#
# Change to where this script is
#
pushd $(dirname $0) > /dev/null

#
# Sanity check for our username.
#
if test ! "$3"
then
	echo "! "
	echo "! Syntax: $0 username start_year end_year [ options ]"
	echo "! "
	exit 1
fi

USER=$1
YEAR_START=$2
YEAR_STOP=$3

if test $YEAR_STOP -lt $YEAR_START
then
	echo "! "
	echo "! Stopping year '${YEAR_STOP}' cannot be less than starting year '${YEAR_START}'!"
	echo "! "
	exit 1
fi


for YEAR in $(seq $YEAR_START $YEAR_STOP)
do

	#
	# There's currently a bug where sometimes you get the previous month,
	# with options like: twint-user dmuth --since 2009-08-01 --until 2009-09-01
	#
	# So for now, this remains commented out or else I'll just get tons of extra months.
	# Once the bug is fixed, I'll switch out the "yearly" code to this "monthly" code.
	#
	#for MONTH in $(seq 1 12)
	#do
	#
	#	SINCE="${YEAR}-${MONTH}-01"
	#
	#	if test "${MONTH}" != 12
	#	then
	#		UNTIL="${YEAR}-$((MONTH + 1))-01"
	#	else
	#		UNTIL="$((YEAR + 1 ))-01-01"
	#	fi
	#
	#	echo "# "
	#	echo "# Starting download of tweets from ${SINCE} to ${UNTIL}"
	#	echo "# "
	#	./twint-user ${USER} --since ${SINCE} --until ${UNTIL}
	#	echo "# Done with range ${SINCE} to ${UNTIL}!"
	#
	#done

	echo "# "
	echo "# Starting download of tweets for user from year ${YEAR}..."
	echo "# "
	./twint-user ${USER} --since ${YEAR}-01-01 --until $((YEAR + 1))-01-01
	echo "# "
	echo "# Done with year ${YEAR}!"
	echo "# "

done

echo "# Done with downloading tweets for ${USER} from ${YEAR_START} to ${YEAR_STOP}!"

